In [8]:
import numpy as np

t_timedata = np.linspace(0, 30,1000)
random_points = np.linspace(0, len(t_timedata)-1, 300).astype(int)
t_data_np = t_timedata[random_points]

print(t_timedata[:5])
print(random_points[:5])
print(t_data_np[:5])

[0.         0.03003003 0.06006006 0.09009009 0.12012012]
[ 0  3  6 10 13]
[0.         0.09009009 0.18018018 0.3003003  0.39039039]


In [7]:
colloc_points = np.linspace(0, 1000, 300).astype(int)
print(colloc_points[:5])

[ 0  3  6 10 13]
