In [2]:
import numpy as np

t_timedata = np.linspace(0, 50,1000)
random_points = np.linspace(0, len(t_timedata)-1, 300).astype(int)
t_data_np = t_timedata[random_points]

print(t_timedata[:5])
print(random_points[:5])
print(t_data_np[:5])

[0.         0.05005005 0.1001001  0.15015015 0.2002002 ]
[ 0  3  6 10 13]
[0.         0.15015015 0.3003003  0.5005005  0.65065065]


In [7]:
colloc_points = np.linspace(0, 1000, 300).astype(int)
print(colloc_points[:5])

[ 0  3  6 10 13]


In [3]:
t_timedata = np.linspace(0, 50, 1000)
train_mask = t_timedata <= 30.0
t_train_window = t_timedata[train_mask]

print(t_timedata[:5])
print(train_mask[:5])
print(t_train_window[:5])

[0.         0.05005005 0.1001001  0.15015015 0.2002002 ]
[ True  True  True  True  True]
[0.         0.05005005 0.1001001  0.15015015 0.2002002 ]
